version: '3'

services:
  ghost:
    build: ./ghost/

    ports:
      - "2368:2368"
    restart: always
    networks:
      - traefik
    volumes:
      - ./content/images:/var/lib/ghost/content/images
      - ./content/themes:/var/lib/ghost/content/themes
      - ./content/data:/var/lib/ghost/content/data

    labels:
      - "traefik.frontend.rule=Host:you-url.com, www.your-url.com"
      - "traefik.port=2368"
      - "traefik.docker.network=traefik"


  traefik:
    image: traefik
    command: --docker --docker.domain=your-url.com --docker.watch
# Comment out the above command line and uncomment the below command to enable the Traefik Dashboard
#    command: --web --docker --docker.domain=your-url.com --docker.watch --logLevel=DEBUG
    networks:
      - traefik
    ports:
      - "80:80"
# Uncomment this to access the Traefik Dashboard
#      - "8080:8080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik:
   driver: bridge
